# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: pepala
description: Mobile app for networking

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line to publish to pub.dev

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.

# Android versioning:
# https://developer.android.com/studio/publish/versioning
# iOS versioning:
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# flutter pub upgrade --major-versions  - update to the latest version
# flutter pub outdated                  - check outdated packages
dependencies:
  flutter:
    sdk: flutter

  ### db ###
  firebase_core: ^1.10.3
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.3

  ### auth ###
  firebase_auth: ^3.3.2
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^3.0.0
  permission_handler: ^9.1.0
  crypto: ^3.0.1

  ### chat ###
  flutter_chat_ui: ^1.5.3
  flutter_firebase_chat_core: ^1.5.1
  file_picker: ^4.3.0
  open_file: ^3.2.1
  uuid: ^3.0.5
  mime: ^1.0.1

  ### other ###
  provider: ^6.0.1
  animations: ^2.0.2 # not yet deployed
  flutter_typeahead: ^3.2.3 # not yet deployed
  sms_autofill: ^2.2.0
  shared_preferences: ^2.0.11

  ### profile ###
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1

  ### widgets ###
  google_maps_flutter: ^2.1.1
  intl_phone_number_input: ^0.7.0+2
  curved_navigation_bar: ^1.0.1 # difficult to customize (might be replaced)
  pin_code_fields: ^7.3.0
  fluttertoast: ^8.0.8

  ### icons ###
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  ### launch screen ###
  flutter_native_splash: ^2.0.4

  # recommended links for good coding practices
  # configuration file: 'analysis_options.yaml'
  flutter_lints: ^1.0.0

flutter:
  # includes material icons of 'Icons' class
  # link: https://fonts.google.com/icons?selected=Material+Icons
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/auth/
    - assets/icons/profile/
    - assets/icons/tracker/
    - assets/background/
    - assets/config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
