// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUHfFZ0NRXK2ow2CPqW53ZGRF42dVNea0',
    appId: '1:893569563845:android:ecb04718d31c14e38804ac',
    messagingSenderId: '893569563845',
    projectId: 'pepala',
    storageBucket: 'pepala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGIQETmtM9lXLYGTH-NmhhI2Px9hRyT0',
    appId: '1:893569563845:ios:aefefb03f8c4b41e8804ac',
    messagingSenderId: '893569563845',
    projectId: 'pepala',
    storageBucket: 'pepala.appspot.com',
    iosClientId: '893569563845-4bsgh09lsklutin9mrvsbjk5u062f7sa.apps.googleusercontent.com',
    iosBundleId: 'com.pepala.pepala',
  );
}
